language: cpp
dist: bionic
compiler:
- gcc
os:
- linux
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_wait 30 ./ci-script-travis.sh;
  fi
env:
  global:
  - secure: efbSNAbENJit6C6PDnmvsAMNmMD9+jLYHE2WsoutzVhMz/HUgNLfRC+Y0gAlVEOVhUpRh3I+5ZMqHt38zkx5JxdlQpR7J2dZQiVKuQL3Drqa9DWMQFmUtwvCQMyG2SS2z2433MfxKrbr3GNpTv9f3ee8fiOnGMYZytCnAiu6V6mgvcwi+5PGhT3yPUtagQxyOJvxqI2mPNe97Uasj5DcFQ2mFkXeveJrxET0fij4F/xJNaDDyvtCeKMNCym7dyl47Tfqj3qK07Mchf1l0GFFno4IlavlzgkXu6UQvnitcc9NN2KCjFZDQpX1e8pxuqEnEP3vSB8PVQummFEJfNge/nGiBFdVwAt4S+hH9jiwSsLxM+KHbOI/sKJn/vWZlOMbZEMQlgdv0vbpvJn3WE3zrOTNUgUUgKYUqkICvv+tSzJr+SgprbQ8A+wxXbMuXSYnVoJVBcxWCmT2IfbxVQZ0iFV3K630bNaFL090JRhnzGKwh/dVbRIlgv5QBP9IlCU4DnCfMGk4XwuTHT20rd7JWCrL2nU10CtZy/w8U01JCRR+9KuHL5+XPmsHrWfXRK/KYbWcNqwjVd8Ae38Wix6DKSbYLvfX1nHD02dMZVPiYwVkWqLajFXkN8CjsqX8jyCcqNwUa2lUT1nERBraqM+4GOp6llDAFTmof6YApnvdUXk=
  - secure: ipeUdYyaLlA15dECvewIo2/Z+9sAfUFCgRvj6PKmfkoK2075Ubk9JW3FiJFRyRSy0nukeQCET6qrxnvs01KlPG6rHtoKS7oNTZ2hgHMDZtXdLxCeqbMt85vpPOkxzvN3KUjrfdUH7QCXPFm67s/nKqzI3/o7HemcqGv2PANqmUdrgQXxYQYFtfqjHdHdGp4iaS3sHAxwIpUJo7em1/4ARVelQxpyRZqKkHh+0BKeq1SIT1kabcLal5bcp8ZwENpUkgOacrfKeRe3Ox2hJMz/SyEoTbBjAwU/nBy/8c7rseKdyjgmhwAjYYQBQ5n1Mnb3+N5c7ZalMpENB9ceZypTazeqaJx/q0cCvXeV5V7B8+9GmYUvBiMiIvv4EQ8dS7oxNKQD+3TNlOEV+LPqdoNnMN0haIm8ahBWRyTyLRQhbqKbETWH9bfVwcmcwBD6hmUQ+JK3TW8m8kG1BNvqPYjCImhDe+56zBAQCwA3FJlUGmhZgae6tN2X/i4DuKg4s9gdwtwKuycPYqAh3d8KAU+mrUP95S4VBe9yb+Jo3do30/6igilQjdxqeNebyQmSEJUxn2VcaS5p80ZSLa6XDAQgpJp1weS+RMd0ToQJ5m55T9Q/cW25x8cvklFtZOnMPRYojwaTYlzG+Hn8XxBHL9d0I2lbynXj8qay94voCiGXuN0=
